#!/bin/bash
  
#  Copyright 2015 wik2kassa
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.

echo "RemoteGit v0.1b"
if [ $# -eq 1 ] && [ $1 == "install" ]; then
	chmod +x $0
	cp $0 "/bin/$0"
  echo "All Done."
  echo "Installed $0 to /bin/$0"
  exit 0
fi
 

# directory creation function

function createEmptyDirectory()
{
  target=$1
  # check if directory already exists
  
  if [ ! -d $target ]; then
      mkdir -p $target
      return 0  
  fi
  
  # check if dir is not empty 
  
  if test "$(ls -A "$target")"; then
      echo "Directory $target is not empty"
      exit 1
  else
      mkdir -p $target
  fi

  return 0
}

if [ $# -ne 2 ]; then
	echo "Insufficient/Excessive Arguiments"
	exit 1
fi


PRODUCTION_LOCATION="$2"

REPO_LOCATION="$1"
WORKING_DIRECTORY=$(pwd)

# TODO:check if directory already exists, if so make sure it's empty

# create the repo directory and initialize a bare git repo in it

createEmptyDirectory $REPO_LOCATION
cd $REPO_LOCATION
git init --bare

ABSOLUTE_REPO_LOCATION=$(pwd)
# add the post recieve hook to the repo

echo "#!/bin/bash

while read oldrev newrev ref
do
  branch=\`echo \$ref | cut -d/ -f3\`
  if [ "production" == "\$branch" -o "master" == "\$branch" ]; then
    
    git --work-tree=$PRODUCTION_LOCATION checkout -f $branch
    
    echo 'Changes pushed to PROD.'
  fi

  if [ "smoke" == "\$branch" ]; then
    
    git --work-tree=$PRODUCTION_LOCATION/smoke/ checkout -f $branch
    
    echo 'Changes pushed to PROD smoke box.'
  fi
done" > hooks/post-recieve
# make the hook executable

chmod +x hooks/post-recieve

# create the folder in the production location

cd $WORKING_DIRECTORY
createEmptyDirectory $PRODUCTION_LOCATION

# TODO: find a way to resolved these on non ubuntu linux machines

USERNAME='username'
PUBLICIP='public.ip.address'
REPONAME='reponame'
#all done
echo "All Done."
echo ""
echo "Use the follwing commands on your local machine to start using your repo."
echo ""
echo ""
echo "git init
git remote add $REPONAME ssh://$USERNAME@$PUBLICIP$ABSOLUTE_REPO_LOCATION
git push $REPONAME +master:refs/heads/master"